[package]
name = "shadcn"
description = "Rust port of shadcn CLI."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.4", features = ["cargo", "derive"] }
env_logger = "0.11.3"
log.workspace = true
reqwest = { version = "0.12.4", features = ["gzip", "json"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
tokio = { version = "1.38.0", features = ["full"] }
toml = "0.8.14"
