[package]
name = "shadcn-ui-cli"
description = "CLI for Rust shadcn/ui."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
clap = { version = "4.5.4", features = ["cargo"] }
env_logger = "0.11.3"
futures = "0.3.30"
log.workspace = true
reqwest = { version = "0.12.4", features = ["gzip", "json"] }
serde = "1.0.203"
serde_json = "1.0.117"
tokio = { version = "1.38.0", features = ["full"] }
toml = "0.8.14"
