[package]
name = "shadcn-ui-yew-book"
description = "Book examples for shadcn/ui Yew."
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
console_error_panic_hook.workspace = true
console_log.workspace = true
log.workspace = true
radix-yew-icons = { workspace = true, optional = true }
shadcn-ui-yew-button = { path = "../../packages/yew/button", optional = true }
shadcn-ui-yew-skeleton = { path = "../../packages/yew/skeleton", optional = true }
web-sys.workspace = true
yew = { workspace = true, features = ["csr"] }
yew-lucide = { git = "https://gitlab.com/stephan.dilly/yew-lucide", branch = "yew-upgrade", optional = true }
yew-router.workspace = true

[features]
default = ["button", "skeleton"]
button = [
    "dep:radix-yew-icons",
    "dep:shadcn-ui-yew-button",
    "dep:yew-lucide",
    "radix-yew-icons/chevron-right",
    "radix-yew-icons/envelope-open",
    "radix-yew-icons/reload",
]
skeleton = ["dep:shadcn-ui-yew-skeleton"]
